CREATE TABLE IF NOT EXISTS `locations` (
  `uuid` varchar(50) NOT NULL,
  `location_order` int(11) NOT NULL,
  `location_type` char(2) NOT NULL,
  `tiploc_code` varchar(7) NOT NULL,
  `tiploc_instance` varchar(1) NOT NULL,
  `arrival` varchar(5) NOT NULL,
  `public_arrival` varchar(5) NOT NULL,
  `pass` varchar(5) NOT NULL,
  `departure` varchar(5) NOT NULL,
  `public_departure` varchar(5) NOT NULL,
  `platform` varchar(3) NOT NULL,
  `line` varchar(3) NOT NULL,
  `path` varchar(3) NOT NULL,
  `engineering_allowance` varchar(2) NOT NULL,
  `pathing_allowance` varchar(2) NOT NULL,
  `performance_allowance` varchar(2) NOT NULL,
  `activity` varchar(12) NOT NULL,
  `created_at` datetime NOT NULL,
  `updated_at` datetime NOT NULL,
  KEY `uuid` (`uuid`),
  KEY `tiploc_code` (`tiploc_code`),
  KEY `arrival` (`arrival`),
  KEY `public_arrival` (`public_arrival`),
  KEY `pass` (`pass`),
  KEY `departure` (`departure`),
  KEY `public_departure` (`public_departure`)
) ENGINE=MyISAM DEFAULT CHARSET=latin1;

CREATE TABLE IF NOT EXISTS `locations_change` (
  `uuid` varchar(50) NOT NULL,
  `tiploc` varchar(7) NOT NULL,
  `tiploc_instance` varchar(1) NOT NULL,
  `category` varchar(2) NOT NULL,
  `train_identity` varchar(4) NOT NULL,
  `headcode` varchar(4) NOT NULL,
  `service_code` varchar(8) NOT NULL,
  `portion_id` varchar(1) NOT NULL,
  `power_type` varchar(3) NOT NULL,
  `timing_load` varchar(4) NOT NULL,
  `speed` varchar(3) NOT NULL,
  `operating_characteristics` varchar(6) NOT NULL,
  `train_class` varchar(1) NOT NULL,
  `sleepers` varchar(1) NOT NULL,
  `reservations` varchar(1) NOT NULL,
  `catering_code` varchar(4) NOT NULL,
  `service_branding` varchar(4) NOT NULL,
  `uic_code` varchar(5) NOT NULL,
  `rsid` varchar(8) NOT NULL,
  KEY `uuid` (`uuid`),
  KEY `identity` (`train_identity`),
  KEY `tiploc` (`tiploc`)
) ENGINE=MyISAM DEFAULT CHARSET=latin1;

CREATE TABLE IF NOT EXISTS `schedules` (
  `uuid` varchar(50) NOT NULL,
  `train_uid` varchar(6) NOT NULL,
  `date_from` date NOT NULL,
  `date_to` date NOT NULL,
  `runs_mo` tinyint(1) NOT NULL,
  `runs_tu` tinyint(1) NOT NULL,
  `runs_we` tinyint(1) NOT NULL,
  `runs_th` tinyint(1) NOT NULL,
  `runs_fr` tinyint(1) NOT NULL,
  `runs_sa` tinyint(1) NOT NULL,
  `runs_su` tinyint(1) NOT NULL,
  `bank_hol` varchar(1) NOT NULL,
  `status` varchar(1) NOT NULL,
  `category` varchar(2) NOT NULL,
  `train_identity` varchar(4) NOT NULL,
  `headcode` varchar(4) NOT NULL,
  `service_code` varchar(8) NOT NULL,
  `portion_id` varchar(1) NOT NULL,
  `power_type` varchar(3) NOT NULL,
  `timing_load` varchar(4) NOT NULL,
  `speed` varchar(3) NOT NULL,
  `operating_characteristics` varchar(6) NOT NULL,
  `train_class` varchar(1) NOT NULL,
  `sleepers` varchar(1) NOT NULL,
  `reservations` varchar(1) NOT NULL,
  `catering_code` varchar(4) NOT NULL,
  `service_branding` varchar(4) NOT NULL,
  `stp_indicator` varchar(1) NOT NULL,
  `uic_code` varchar(5) NOT NULL,
  `atoc_code` varchar(2) NOT NULL,
  `ats_code` varchar(1) NOT NULL,
  `rsid` varchar(8) NOT NULL,
  `data_source` varchar(1) NOT NULL,
  `created_at` datetime NOT NULL,
  `updated_at` datetime NOT NULL,
  KEY `uuid` (`uuid`),
  KEY `identity` (`train_identity`),
  KEY `train_uid` (`train_uid`),
  KEY `date_from` (`date_from`),
  KEY `date_to` (`date_to`),
  KEY `runs_mo` (`runs_mo`),
  KEY `runs_tu` (`runs_tu`),
  KEY `runs_we` (`runs_we`),
  KEY `runs_th` (`runs_th`),
  KEY `runs_fr` (`runs_fr`),
  KEY `runs_sa` (`runs_sa`),
  KEY `runs_su` (`runs_su`),
  KEY `atoc_code` (`atoc_code`),
  KEY `status` (`status`),
  KEY `bank_hol` (`bank_hol`)
) ENGINE=MyISAM DEFAULT CHARSET=latin1;

CREATE TABLE IF NOT EXISTS `schedules_stpcancel` (
  `uuid` varchar(50) NOT NULL,
  `cancel_from` date NOT NULL,
  `cancel_to` date NOT NULL,
  `cancel_mo` tinyint(1) NOT NULL,
  `cancel_tu` tinyint(1) NOT NULL,
  `cancel_we` tinyint(1) NOT NULL,
  `cancel_th` tinyint(1) NOT NULL,
  `cancel_fr` tinyint(1) NOT NULL,
  `cancel_sa` tinyint(1) NOT NULL,
  `cancel_su` tinyint(1) NOT NULL,
  KEY `uuid` (`uuid`),
  KEY `cancel_from` (`cancel_from`),
  KEY `cancel_to` (`cancel_to`),
  KEY `cancel_mo` (`cancel_mo`),
  KEY `cancel_tu` (`cancel_tu`),
  KEY `cancel_we` (`cancel_we`),
  KEY `cancel_th` (`cancel_th`),
  KEY `cancel_fr` (`cancel_fr`),
  KEY `cancel_sa` (`cancel_sa`),
  KEY `cancel_su` (`cancel_su`)
) ENGINE=MyISAM DEFAULT CHARSET=latin1 COMMENT='Contains LTP services with an STP cancel (C on CIF)';

CREATE TABLE IF NOT EXISTS `tiplocs` (
  `tiploc` varchar(7) NOT NULL,
  `nalco` varchar(6) NOT NULL,
  `tps_description` varchar(26) NOT NULL,
  `stanox` varchar(5) NOT NULL,
  `crs` varchar(3) NOT NULL,
  `description` varchar(16) NOT NULL,
  PRIMARY KEY (`tiploc`),
  KEY `crs_code` (`crs`),
  KEY `stanox` (`stanox`)
) ENGINE=MyISAM DEFAULT CHARSET=latin1;

CREATE TABLE IF NOT EXISTS `associations` (
  `uuid` varchar(50) NOT NULL,
  `main_train_uid` varchar(6) NOT NULL,
  `assoc_train_uid` varchar(6) NOT NULL,
  `date_from` date NOT NULL,
  `date_to` date NOT NULL,
  `assoc_mo` tinyint(1) NOT NULL,
  `assoc_tu` tinyint(1) NOT NULL,
  `assoc_we` tinyint(1) NOT NULL,
  `assoc_th` tinyint(1) NOT NULL,
  `assoc_fr` tinyint(1) NOT NULL,
  `assoc_sa` tinyint(1) NOT NULL,
  `assoc_su` tinyint(1) NOT NULL,
  `category` varchar(2) NOT NULL,
  `date_indicator` varchar(1) NOT NULL,
  `location` varchar(7) NOT NULL,
  `base_location_suffix` varchar(1) NOT NULL,
  `assoc_location_suffix` varchar(1) NOT NULL,
  `assoc_type` varchar(1) NOT NULL,
  `stp_indicator` varchar(1) NOT NULL,
  UNIQUE KEY `uuid` (`uuid`),
  KEY `main_train_uid` (`main_train_uid`),
  KEY `date_from` (`date_from`),
  KEY `date_to` (`date_to`),
  KEY `assoc_train_uid` (`assoc_train_uid`),
  KEY `assoc_mo` (`assoc_mo`),
  KEY `assoc_tu` (`assoc_tu`),
  KEY `assoc_we` (`assoc_we`),
  KEY `assoc_th` (`assoc_th`),
  KEY `assoc_fr` (`assoc_fr`),
  KEY `assoc_sa` (`assoc_sa`),
  KEY `assoc_su` (`assoc_su`),
  KEY `location` (`location`)
) ENGINE=MyISAM DEFAULT CHARSET=latin1;

CREATE TABLE IF NOT EXISTS `associations_stpcancel` (
  `uuid` varchar(50) NOT NULL,
  `cancel_from` date NOT NULL,
  `cancel_to` date NOT NULL,
  `cancel_mo` tinyint(1) NOT NULL,
  `cancel_tu` tinyint(1) NOT NULL,
  `cancel_we` tinyint(1) NOT NULL,
  `cancel_th` tinyint(1) NOT NULL,
  `cancel_fr` tinyint(1) NOT NULL,
  `cancel_sa` tinyint(1) NOT NULL,
  `cancel_su` tinyint(1) NOT NULL,
  KEY `uuid` (`uuid`),
  KEY `cancel_mo` (`cancel_mo`),
  KEY `cancel_tu` (`cancel_tu`),
  KEY `cancel_we` (`cancel_we`),
  KEY `cancel_th` (`cancel_th`),
  KEY `cancel_fr` (`cancel_fr`),
  KEY `cancel_sa` (`cancel_sa`),
  KEY `cancel_su` (`cancel_su`),
  KEY `cancel_from` (`cancel_from`),
  KEY `cancel_to` (`cancel_to`)
) ENGINE=MyISAM DEFAULT CHARSET=latin1 COMMENT='Contains LTP services with an STP cancel (C on CIF)';

