CREATE TABLE IF NOT EXISTS `locations` (
  `uuid` varchar(50) NOT NULL,
  `location_order` int(11) NOT NULL,
  `location_type` char(2) NOT NULL,
  `tiploc_code` varchar(7) NOT NULL,
  `tiploc_instance` varchar(1) NOT NULL,
  `arrival` varchar(5) NOT NULL,
  `public_arrival` varchar(5) NOT NULL,
  `pass` varchar(5) NOT NULL,
  `departure` varchar(5) NOT NULL,
  `public_departure` varchar(5) NOT NULL,
  `platform` varchar(3) NOT NULL,
  `line` varchar(3) NOT NULL,
  `path` varchar(3) NOT NULL,
  `engineering_allowance` varchar(2) NOT NULL,
  `pathing_allowance` varchar(2) NOT NULL,
  `performance_allowance` varchar(2) NOT NULL,
  `activity` varchar(12) NOT NULL,
  `created_at` datetime NOT NULL,
  `updated_at` datetime NOT NULL,
  KEY `uuid` (`uuid`),
  KEY `tiploc_code` (`tiploc_code`),
  KEY `arrival` (`arrival`),
  KEY `public_arrival` (`public_arrival`),
  KEY `pass` (`pass`),
  KEY `departure` (`departure`),
  KEY `public_departure` (`public_departure`)
) ENGINE=MyISAM DEFAULT CHARSET=latin1;

CREATE TABLE IF NOT EXISTS `schedules` (
  `uuid` varchar(50) NOT NULL,
  `train_uid` varchar(6) NOT NULL,
  `date_from` date NOT NULL,
  `date_to` date NOT NULL,
  `runs_mo` tinyint(1) NOT NULL,
  `runs_tu` tinyint(1) NOT NULL,
  `runs_we` tinyint(1) NOT NULL,
  `runs_th` tinyint(1) NOT NULL,
  `runs_fr` tinyint(1) NOT NULL,
  `runs_sa` tinyint(1) NOT NULL,
  `runs_su` tinyint(1) NOT NULL,
  `bank_hol` varchar(1) NOT NULL,
  `status` varchar(1) NOT NULL,
  `category` varchar(2) NOT NULL,
  `train_identity` varchar(4) NOT NULL,
  `headcode` varchar(4) NOT NULL,
  `service_code` varchar(8) NOT NULL,
  `portion_id` varchar(1) NOT NULL,
  `power_type` varchar(3) NOT NULL,
  `timing_load` varchar(4) NOT NULL,
  `speed` varchar(3) NOT NULL,
  `operating_characteristics` varchar(6) NOT NULL,
  `train_class` varchar(1) NOT NULL,
  `sleepers` varchar(1) NOT NULL,
  `reservations` varchar(1) NOT NULL,
  `catering_code` varchar(4) NOT NULL,
  `service_branding` varchar(4) NOT NULL,
  `stp_indicator` varchar(1) NOT NULL,
  `uic_code` varchar(5) NOT NULL,
  `atoc_code` varchar(2) NOT NULL,
  `ats_code` varchar(1) NOT NULL,
  `rsid` varchar(8) NOT NULL,
  `data_source` varchar(1) NOT NULL,
  `created_at` datetime NOT NULL,
  `updated_at` datetime NOT NULL,
  KEY `uuid` (`uuid`),
  KEY `identity` (`train_identity`),
  KEY `train_uid` (`train_uid`)
) ENGINE=MyISAM DEFAULT CHARSET=latin1;

CREATE TABLE IF NOT EXISTS `schedules_stpcancel` (
  `uuid` varchar(50) NOT NULL,
  `cancel_from` date NOT NULL,
  `cancel_to` date NOT NULL,
  KEY `uuid` (`uuid`)
) ENGINE=MyISAM DEFAULT CHARSET=latin1 COMMENT='Contains LTP services with an STP cancel (C on CIF)';

CREATE TABLE IF NOT EXISTS `tiplocs` (
  `tiploc` varchar(7) NOT NULL,
  `nalco` varchar(6) NOT NULL,
  `tps_description` varchar(26) NOT NULL,
  `stanox` varchar(5) NOT NULL,
  `crs` varchar(3) NOT NULL,
  `description` varchar(16) NOT NULL,
  PRIMARY KEY (`tiploc`),
  KEY `crs_code` (`crs`),
  KEY `stanox` (`stanox`)
) ENGINE=MyISAM DEFAULT CHARSET=latin1;
